# Generated by Django 4.2.1 on 2025-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrammessage",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
