# Generated by Django 4.2.1 on 2025-10-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_chat", "0002_telegrammessage_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="telegram_audios/"),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="telegram_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="telegrammessage",
            name="sender",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="telegrammessage",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
