# Generated by Django 4.2.1 on 2025-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(unique=True)),
                ("mac", models.CharField(blank=True, max_length=50, null=True)),
                ("hostname", models.CharField(blank=True, max_length=200, null=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
